### ISSUE TITLE
催更催更

### ISSUE THREAD

**Issue by coder-tx** [yabi-zzh/harmonyVnc#1]
很好用啊 作者大大有无更新计划

**Comment by yabi-zzh** [comment]
已更新简易 JFrame版

**Comment by coder-tx** [comment]
大佬真牛逼，试了下很好使。但是滚动事件好像不行唉

**Comment by coder-tx** [comment]
我这用触摸板就没法滑，拖住滑也不好使。点击啥的都没问题

**Comment by yabi-zzh** [comment]
> 我这用触摸板就没法滑，拖住滑也不好使。点击啥的都没问题

了解，后续看下如何优化，目前来看 滑动、拖拽 没有更优的方案。
